# Generated by Django 6.0 on 2025-12-14 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pregunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enunciado", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("seleccion_multiple", "Selección Múltiple"),
                            ("analisis_grafica", "Análisis de Gráfica"),
                            ("lectura", "Lectura Crítica"),
                        ],
                        default="seleccion_multiple",
                        max_length=50,
                    ),
                ),
                (
                    "dificultad",
                    models.CharField(
                        choices=[
                            ("facil", "Fácil"),
                            ("media", "Media"),
                            ("dificil", "Difícil"),
                        ],
                        default="media",
                        max_length=20,
                    ),
                ),
                (
                    "explicacion",
                    models.TextField(
                        blank=True, help_text="Explicación de la respuesta correcta"
                    ),
                ),
                (
                    "imagen_url",
                    models.URLField(
                        blank=True, help_text="URL de imagen si aplica", null=True
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="OpcionRespuesta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField()),
                ("es_correcta", models.BooleanField(default=False)),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opciones",
                        to="preguntas.pregunta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subareas",
                        to="preguntas.area",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pregunta",
            name="subarea",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preguntas",
                to="preguntas.subarea",
            ),
        ),
    ]
