# Generated by Django 5.2.8 on 2025-12-14 15:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preguntas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="area",
            options={"verbose_name": "Área", "verbose_name_plural": "Áreas"},
        ),
        migrations.AlterModelOptions(
            name="opcionrespuesta",
            options={
                "ordering": ["orden", "id"],
                "verbose_name": "Opción de respuesta",
                "verbose_name_plural": "Opciones de respuesta",
            },
        ),
        migrations.AlterModelOptions(
            name="pregunta",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Pregunta",
                "verbose_name_plural": "Preguntas",
            },
        ),
        migrations.AlterModelOptions(
            name="subarea",
            options={"verbose_name": "Sub-área", "verbose_name_plural": "Sub-áreas"},
        ),
        migrations.AddField(
            model_name="opcionrespuesta",
            name="orden",
            field=models.IntegerField(
                default=0, help_text="Orden de presentación (0 para aleatorio)"
            ),
        ),
        migrations.AddField(
            model_name="pregunta",
            name="area",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preguntas",
                to="preguntas.area",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pregunta",
            name="competencia",
            field=models.CharField(
                choices=[
                    ("interpretar", "Interpretar"),
                    ("argumentar", "Argumentar"),
                    ("proponer", "Proponer"),
                    ("modelar", "Modelar"),
                    ("razonar", "Razonar"),
                    ("comunicar", "Comunicar"),
                    ("inferir", "Inferir"),
                    ("analizar", "Analizar"),
                ],
                default="interpretar",
                help_text="Competencia que evalúa la pregunta",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="pregunta",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pregunta",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="area",
            name="nombre",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="pregunta",
            name="enunciado",
            field=models.TextField(help_text="Texto de la pregunta"),
        ),
        migrations.AlterField(
            model_name="pregunta",
            name="imagen_url",
            field=models.URLField(
                blank=True,
                help_text="URL de imagen específica de la pregunta (si aplica)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pregunta",
            name="subarea",
            field=models.ForeignKey(
                blank=True,
                help_text="Opcional: para compatibilidad con estructura anterior",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="preguntas",
                to="preguntas.subarea",
            ),
        ),
        migrations.AlterField(
            model_name="pregunta",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("seleccion_unica", "Selección múltiple única"),
                    ("asociada_contexto", "Asociada a contexto"),
                    ("interpretacion", "Interpretación de datos"),
                    ("analisis", "Análisis de situación"),
                    ("inferencia", "Inferencia"),
                    ("error_conceptual", "Identificación de error"),
                    ("lectura_critica", "Lectura crítica"),
                    ("razonamiento_cuantitativo", "Razonamiento cuantitativo"),
                    ("ingles_parte1", "Inglés - Parte 1 (Léxico)"),
                    ("ingles_parte2", "Inglés - Parte 2 (Avisos)"),
                    ("ingles_parte3", "Inglés - Parte 3 (Conversación)"),
                    ("ingles_parte4", "Inglés - Parte 4 (Gramática)"),
                    ("ingles_parte5", "Inglés - Parte 5 (Comprensión)"),
                    ("ingles_parte6", "Inglés - Parte 6 (Inferencial)"),
                    ("ingles_parte7", "Inglés - Parte 7 (Léxico/Gramática)"),
                ],
                default="seleccion_unica",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="Contexto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("texto", "Texto"),
                            ("imagen", "Imagen"),
                            ("tabla", "Tabla"),
                            ("grafica", "Gráfica"),
                            ("audio", "Audio"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        blank=True, help_text="Título del contexto", max_length=200
                    ),
                ),
                (
                    "contenido",
                    models.TextField(
                        help_text="Texto del contexto o descripción si es imagen/gráfica/tabla"
                    ),
                ),
                (
                    "archivo",
                    models.ImageField(
                        blank=True,
                        help_text="Opcional: imagen, tabla o gráfica",
                        null=True,
                        upload_to="contextos/",
                    ),
                ),
                (
                    "url_externa",
                    models.URLField(
                        blank=True,
                        help_text="URL alternativa para recursos externos",
                        null=True,
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contextos",
                        to="preguntas.area",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contexto",
                "verbose_name_plural": "Contextos",
            },
        ),
        migrations.AddField(
            model_name="pregunta",
            name="contexto",
            field=models.ForeignKey(
                blank=True,
                help_text="Contexto compartido (texto, imagen, tabla, etc.)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="preguntas",
                to="preguntas.contexto",
            ),
        ),
    ]
