# Generated by Django 5.2.8 on 2025-12-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preguntas", "0002_alter_area_options_alter_opcionrespuesta_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contexto",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("texto", "Texto"),
                    ("imagen", "Imagen"),
                    ("tabla", "Tabla"),
                    ("grafica", "Gráfica"),
                    ("audio", "Audio"),
                ],
                max_length=50,
            ),
        ),
    ]
