# Generated by Django 4.2.30 on 2026-05-28 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("preguntas", "0004_flashcard"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreguntaIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "debilidad_objetivo",
                    models.CharField(
                        help_text="Concepto o tema de debilidad específica, e.g. proporcionalidad",
                        max_length=150,
                    ),
                ),
                (
                    "enunciado",
                    models.TextField(help_text="Texto de la pregunta generada"),
                ),
                (
                    "dificultad",
                    models.CharField(
                        choices=[
                            ("facil", "Fácil"),
                            ("media", "Media"),
                            ("dificil", "Difícil"),
                        ],
                        default="media",
                        max_length=20,
                    ),
                ),
                (
                    "pista",
                    models.TextField(
                        blank=True, help_text="Scaffolding Nivel 1: pista socrática"
                    ),
                ),
                (
                    "ejemplo",
                    models.TextField(
                        blank=True, help_text="Scaffolding Nivel 2: ejemplo resuelto"
                    ),
                ),
                (
                    "explicacion",
                    models.TextField(
                        blank=True,
                        help_text="Scaffolding Nivel 3: explicación completa",
                    ),
                ),
                (
                    "tasa_exito",
                    models.FloatField(
                        default=0.0,
                        help_text="Tasa de éxito del estudiante en esta pregunta",
                    ),
                ),
                ("veces_respondida", models.IntegerField(default=0)),
                ("veces_correcta", models.IntegerField(default=0)),
                (
                    "estado_validacion",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aprobada", "Aprobada"),
                            ("rechazada", "Rechazada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("promocionada", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preguntas_ia",
                        to="preguntas.area",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preguntas_ia",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pregunta IA",
                "verbose_name_plural": "Preguntas IA",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OpcionRespuestaIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField()),
                ("es_correcta", models.BooleanField(default=False)),
                (
                    "pregunta_ia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opciones",
                        to="preguntas.preguntaia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opción de respuesta IA",
                "verbose_name_plural": "Opciones de respuesta IA",
            },
        ),
        migrations.CreateModel(
            name="ProgresoDebilidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("debilidad", models.CharField(max_length=150)),
                ("intentos_totales", models.IntegerField(default=0)),
                ("aciertos_totales", models.IntegerField(default=0)),
                (
                    "porcentaje_mejora",
                    models.FloatField(
                        default=0.0,
                        help_text="Mejora porcentual de precisión reciente vs histórica",
                    ),
                ),
                (
                    "nivel_actual",
                    models.CharField(
                        choices=[
                            ("bajo", "Bajo"),
                            ("medio", "Medio"),
                            ("alto", "Alto"),
                        ],
                        default="bajo",
                        max_length=20,
                    ),
                ),
                (
                    "historial_recuperacion",
                    models.JSONField(
                        default=list,
                        help_text="Historial de intentos: [{'fecha': '...', 'es_correcta': bool, 'dificultad': '...'}]",
                    ),
                ),
                ("ultimo_entrenamiento", models.DateTimeField(auto_now=True)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progresos_debilidades",
                        to="preguntas.area",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progresos_debilidades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Progreso de Debilidad",
                "verbose_name_plural": "Progresos de Debilidades",
                "unique_together": {("usuario", "debilidad")},
            },
        ),
    ]
