# Generated by Django 5.2.17 on 2026-09-02 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0005_preguntaia_opcionrespuestaia_progresodebilidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pregunta',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Pregunta', 'verbose_name_plural': 'Preguntas'},
        ),
    ]
