# Generated by Django 5.2.10 on 2026-02-16 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartidaDesafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_juego', models.CharField(choices=[('quick', 'Desafío Rápido'), ('millionaire', 'Sabio Millonario'), ('bomb', 'Bomba de Tiempo'), ('streak', 'Racha Imbatible')], default='quick', max_length=20)),
                ('puntaje_total', models.IntegerField(default=0)),
                ('preguntas_correctas', models.IntegerField(default=0)),
                ('preguntas_incorrectas', models.IntegerField(default=0)),
                ('max_combo', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_desafio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partida de Desafío',
                'verbose_name_plural': 'Partidas de Desafío',
                'ordering': ['-puntaje_total', '-fecha'],
            },
        ),
    ]
