# Generated by Django 5.2.10 on 2026-02-16 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, unique=True)),
                ('num_jugadores_max', models.IntegerField(default=4)),
                ('areas', models.JSONField(default=list)),
                ('dificultad', models.CharField(default='media', max_length=20)),
                ('num_preguntas', models.IntegerField(default=10)),
                ('estado', models.CharField(choices=[('LOBBY', 'En Espera'), ('PLAYING', 'Jugando'), ('FINISHED', 'Finalizado')], default='LOBBY', max_length=20)),
                ('pregunta_actual_idx', models.IntegerField(default=0)),
                ('preguntas_ids', models.JSONField(default=list)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField(default=0)),
                ('listo', models.BooleanField(default=False)),
                ('respondio_actual', models.BooleanField(default=False)),
                ('bloqueado_hasta_pregunta', models.IntegerField(default=-1)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='juegos.sala')),
            ],
            options={
                'unique_together': {('sala', 'usuario')},
            },
        ),
    ]
