# Generated by Django 5.2.10 on 2026-03-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0002_sala_participante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partidadesafio',
            name='tipo_juego',
            field=models.CharField(choices=[('quick', 'Desafío Rápido'), ('millionaire', 'Sabio Millonario'), ('bomb', 'Bomba de Tiempo'), ('streak', 'Racha Imbatible'), ('multi', 'Duelo Multijugador')], default='quick', max_length=20),
        ),
    ]
