# Generated by Django 5.2.8 on 2026-02-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_teacher",
            field=models.BooleanField(
                default=False,
                help_text="Designa si este usuario es docente y puede agregar preguntas",
            ),
        ),
    ]
