# Generated by Django 5.2.8 on 2026-05-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_is_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_content_admin",
            field=models.BooleanField(
                default=False,
                help_text="Designa si este usuario puede realizar importaciones masivas de contenido",
            ),
        ),
    ]
