# Generated by Django 4.2.30 on 2026-06-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_is_content_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_url",
            field=models.URLField(
                blank=True,
                help_text="URL del avatar seleccionado por el usuario",
                null=True,
            ),
        ),
    ]
