# Generated by Django 5.2.13 on 2026-06-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_to_devices',
            field=models.CharField(blank=True, choices=[('home_computer', 'Computadora en casa'), ('mobile_only', 'Solo móvil'), ('shared_device', 'Dispositivo compartido'), ('limited_access', 'Acceso limitado'), ('no_access', 'Sin acceso')], help_text='Acceso a dispositivos y conectividad', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento del estudiante', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='extra_support',
            field=models.BooleanField(default=False, help_text='El usuario recibe apoyo adicional fuera del aula'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Masculino'), ('female', 'Femenino'), ('non_binary', 'No binario'), ('prefer_not_to_say', 'Prefiero no decirlo')], help_text='Género informado por el usuario', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.CharField(blank=True, help_text='Grado o curso escolar', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='language_preference',
            field=models.CharField(blank=True, choices=[('spanish', 'Español'), ('english', 'Inglés'), ('other', 'Otro')], help_text='Idioma preferido para el aprendizaje', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='learning_goals',
            field=models.TextField(blank=True, help_text='Objetivos de aprendizaje del usuario'),
        ),
        migrations.AddField(
            model_name='user',
            name='learning_style',
            field=models.CharField(blank=True, choices=[('visual', 'Visual'), ('auditory', 'Auditivo'), ('kinesthetic', 'Kinestésico'), ('mixed', 'Mixto'), ('not_sure', 'No estoy seguro')], help_text='Estilo de aprendizaje preferido', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(blank=True, help_text='Institución educativa', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='special_education_needs',
            field=models.TextField(blank=True, help_text='Necesidades educativas especiales o apoyos requeridos'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_type',
            field=models.CharField(blank=True, choices=[('regular', 'Alumno regular'), ('remedial', 'Refuerzo'), ('recovery', 'Recuperación'), ('other', 'Otro')], help_text='Tipo de estudiante según su trayectoria académica', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='study_habits',
            field=models.CharField(blank=True, help_text='Hábitos de estudio', max_length=255),
        ),
    ]
