# Generated by Django 6.0 on 2025-12-14 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("preguntas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Simulacro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateTimeField(auto_now_add=True)),
                ("fecha_fin", models.DateTimeField(blank=True, null=True)),
                ("puntaje_total", models.FloatField(default=0.0)),
                ("tiempo_usado_segundos", models.IntegerField(default=0)),
                ("completado", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="DetalleSimulacro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("es_correcta", models.BooleanField(default=False)),
                (
                    "opcion_seleccionada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="preguntas.opcionrespuesta",
                    ),
                ),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="preguntas.pregunta",
                    ),
                ),
            ],
        ),
    ]
